import './rem'
import '../css/reset.less'
import '../css/index.less'
import '../css/wf-form.less'
import '../bootstrap-3.3.7-dist/css/bootstrap.css'
import '../css/zl-plane.css'
import 'zepto/dist/zepto'
import 'zepto/src/touch'
import '../../node_modules/zepto/src/fx'
import '../../node_modules/zepto/src/fx_methods'
// import 'zepto/src/fx_methods'
import './start-animate' 
import './zl-index'
import './mq-production'
import './rj-index'
import './zl-plane'
import './form'
